version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /
      - /stack/lambdas/rekopoc-apply-faces-to-video-docker
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /stack/lambdas/rekopoc-apply-faces-to-video-docker
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
